apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leanix-exporter
  namespace: giantswarm
  labels:
    app: leanix-exporter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: leanix-exporter
    spec:
      volumes:
      - name: leanix-exporter-configmap
        configMap:
          name: leanix-exporter-configmap
          items:
          - key: config.yml
            path: config.yml
      containers:
      - name: leanix-exporter
        image: giantswarm/leanix-exporter:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: leanix-exporter-configmap
          mountPath: /var/run/leanix-exporter/configmap/
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 250m
            memory: 250Mi

---

apiVersion: v1
kind: Service
metadata:
  name: leanix-exporter-configmap
  namespace: giantswarm
  labels:
    app: leanix-exporter-configmap
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: leanix-exporter

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: leanix-exporter-configmap
  namespace: giantswarm
data:
  config.yml: |
    excludes:
      - kube-system
      - kube-public